name: Generate Snake

on:
  # Runs every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Gsubrat  # Replace 'Gsubrat' with your GitHub username
          outputs: dist/snake.svg

      - name: Push Snake to the output branch
        uses: ad-m/github-push-action@master
        with:
          branch: output
          file: dist/snake.svg

      - name: Add and commit the generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Generated snake animation"

      - name: Push changes
        run: git push
